version: '3.8'

services:
  localstack:
    image: localstack/localstack:0.12.17
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'

  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
